#cloud-config

write_files:
{{if not .IsCoreOS}}
- path: "/etc/systemd/system/docker.service.d/clear_mount_propagation_flags.conf"
  permissions: "0644"
  owner: "root"
  content: |
    [Service]
    MountFlags=shared
{{end}}
- path: "/etc/systemd/system/docker.service.d/exec_start.conf"
  permissions: "0644"
  owner: "root"
  content: |
    [Service]
    ExecStart=
{{if .IsClearLinux}}
    ExecStart=/usr/bin/dockerd -H fd:// --storage-driver=overlay2 --bip={{WrapAsVariable "dockerBridgeCidr"}}
{{else}}
    ExecStart=/usr/bin/docker daemon -H fd:// --storage-driver=overlay2 --bip={{WrapAsVariable "dockerBridgeCidr"}}
{{end}}

- path: "/etc/docker/daemon.json"
  permissions: "0644"
  owner: "root"
  content: |
    {
      "live-restore": true,
      "log-driver": "json-file",
      "log-opts":  {
         "max-size": "50m",
         "max-file": "5"
      }
    }

- path: "/etc/kubernetes/certs/ca.crt"
  permissions: "0644"
  encoding: "base64"
  owner: "root"
  content: |
    {{WrapAsVariable "caCertificate"}}

- path: "/etc/kubernetes/certs/client.crt"
  permissions: "0644"
  encoding: "base64"
  owner: "root"
  content: |
    {{WrapAsVariable "clientCertificate"}}

- path: "/var/lib/kubelet/kubeconfig"
  permissions: "0644"
  owner: "root"
  content: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: localcluster
      cluster:
        certificate-authority: /etc/kubernetes/certs/ca.crt
        server: https://{{WrapAsVariable "kubernetesAPIServerIP"}}:443
    users:
    - name: client
      user:
        client-certificate: /etc/kubernetes/certs/client.crt
        client-key: /etc/kubernetes/certs/client.key
    contexts:
    - context:
        cluster: localcluster
        user: client
      name: localclustercontext
    current-context: localclustercontext

- path: "/etc/systemd/system/kubectl-extract.service"
  permissions: "0644"
  owner: "root"
  content: |
    [Unit]
    Description=Kubectl extraction
    Requires=docker.service
    After=docker.service
{{if .IsCoreOS}}
    ConditionPathExists=!/opt/kubectl
{{else}}
    ConditionPathExists=!/usr/local/bin/kubectl
{{end}}

    [Service]
    TimeoutStartSec=0
    Restart=on-failure
    RestartSec=5s
    ExecStartPre=/bin/mkdir -p /tmp/kubectldir
    ExecStartPre=/usr/bin/docker pull {{WrapAsVariable "kubernetesHyperkubeSpec"}}
    ExecStartPre=/usr/bin/docker run --rm -v /tmp/kubectldir:/opt/kubectldir {{WrapAsVariable "kubernetesHyperkubeSpec"}} /bin/bash -c "cp /hyperkube /opt/kubectldir/"
{{if .IsCoreOS}}
    ExecStartPre=/bin/mv /tmp/kubectldir/hyperkube /opt/kubectl
    ExecStart=/bin/chmod a+x /opt/kubectl
{{else}}
    ExecStartPre=/bin/mv /tmp/kubectldir/hyperkube /usr/local/bin/kubectl
    ExecStart=/bin/chmod a+x /usr/local/bin/kubectl
{{end}}

    [Install]
    WantedBy=multi-user.target

- path: "/etc/default/kubelet"
  permissions: "0644"
  owner: "root"
  content: |
{{if IsKubernetesVersionLt "1.8.0"}}
    KUBELET_OPTS=--require-kubeconfig
{{else}}
    KUBELET_OPTS=
{{end}}
    KUBELET_CONFIG={{GetKubeletConfigKeyVals .KubernetesConfig }}
    KUBELET_IMAGE={{WrapAsVariable "kubernetesHyperkubeSpec"}}
    DOCKER_OPTS=
    KUBELET_REGISTER_SCHEDULABLE=true
    KUBELET_NODE_LABELS={{GetAgentKubernetesLabels . "',variables('labelResourceGroup'),'"}}
{{if IsKubernetesVersionGe "1.6.0"}}
    KUBELET_NON_MASQUERADE_CIDR={{WrapAsVariable "kubernetesNonMasqueradeCidr"}}
{{end}}

AGENT_ARTIFACTS_CONFIG_PLACEHOLDER

- path: "/opt/azure/containers/kubelet.sh"
  permissions: "0755"
  owner: "root"
  content: |
    #!/bin/bash

{{if IsAzureCNI}}
    # SNAT outbound traffic from pods to destinations outside of VNET.
    iptables -t nat -A POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d {{WrapAsVariable "vnetCidr"}} -j MASQUERADE
{{end}}

    exit 0

{{if .IsClearLinux}}
- path: "/opt/azure/containers/clear-linux-setup.sh"
  permissions: "0744"
  owner: "root"
  content: |
    #!/usr/bin/env bash
    # update the package manager
    swupd update
    tmpdir="$(mktemp -d)"
    base64files=( "/etc/kubernetes/certs/ca.crt" "/etc/kubernetes/certs/client.crt" )
    gzipfiles=(  "/opt/azure/containers/provision.sh" "/opt/azure/containers/docker.sh" )
    # base64 decode the files
    for f in "${base64files[@]}"; do
      if [[ -f "$f" ]]; then
        base=$(basename "$f")
        cat "$f" | base64 -d > "${tmpdir}/${base}"
        cat "${tmpdir}/${base}" > "$f"
      fi
    done
    # gzip decode the files
    for f in "${gzipfiles[@]}"; do
      if [[ -f "$f" ]]; then
        base=$(basename "$f")
        cat "$f" | base64 -d | gzip -d > "${tmpdir}/${base}"
        cat "${tmpdir}/${base}" > "$f"
      fi
    done
    for f in /etc/kubernetes/manifests/*.yaml; do
      base=$(basename "$f")
      cat "$f" | base64 -d | gzip -d > "${tmpdir}/${base}"
      cat "${tmpdir}/${base}" > "$f"
    done
    rm -rf "$tmpdir"

    touch /opt/azure/containers/dockerinstall.complete;

    /opt/azure/containers/provision.sh;
{{end}}

- path: "/opt/azure/containers/docker.sh"
  permissions: "0744"
  encoding: gzip
  owner: "root"
  content: !!binary |
    {{WrapAsVariable "dockerScript"}}

- path: "/opt/azure/containers/provision.sh"
  permissions: "0744"
  encoding: gzip
  owner: "root"
  content: !!binary |
    {{WrapAsVariable "provisionScript"}}

{{if .IsCoreOS}}
- path: "/opt/azure/containers/provision-setup.sh"
  permissions: "0755"
  owner: "root"
  content: |
    #!/bin/bash
    /usr/bin/mkdir -p /etc/kubernetes/manifests
    usermod -aG docker {{WrapAsVariable "username"}}

    systemctl enable rpcbind
    systemctl enable rpc-statd
    systemctl start rpcbind
    systemctl start rpc-statd

    # Simulates runcmd completion
    touch /opt/azure/containers/runcmd.complete

coreos:
  units:
    - name: start-provision-setup.service
      command: "start"
      content: |
        # Note: Initiated as a service since there is no runcmd within CoreOS on cloud-config/Ignition
        [Unit]
        Description=Start provision setup service

        [Service]
        ExecStart=/opt/azure/containers/provision-setup.sh
{{else}}
{{if not EnablePodSecurityPolicy}}
    sed -i "s|apparmor_parser|d|g" "/etc/systemd/system/kubelet.service"
{{end}}
# ALL commands here must end in an ";" so the cloud init on clear linux doesn't fail.
runcmd:
- set -x;
- echo `date`,`hostname`, startruncmd>>/opt/m;
{{if .IsClearLinux}}
- /opt/azure/containers/clear-linux-setup.sh;
{{end}}
# the first arg is the number of retries, the second arg is the wait duration between two retries and the rest of the args are the cmd to run
- retrycmd_if_failure() { retries=$1; wait=$2; shift && shift; for i in $(seq 1 $retries); do ${@}; [ $? -eq 0  ] && break || sleep $wait; done; echo Executed \"$@\" $i times; };
- retrycmd_if_failure 120 1 nc -zuw1 $(grep nameserver /etc/resolv.conf | cut -d \  -f 2) 53;
- echo "doing agent provision scripts if any...";{{GetKubernetesAgentPreprovisionYaml .}};
- systemctl enable rpcbind;
- systemctl enable rpc-statd;
- systemctl start rpcbind;
- systemctl start rpc-statd;
{{if not .IsClearLinux}}
- /opt/azure/containers/docker.sh {{WrapAsVariable "dockerEngineDownloadRepo"}} {{WrapAsVariable "dockerEngineVersion"}};
{{end}}
- systemctl restart docker;
- mkdir -p /etc/kubernetes/manifests;
- usermod -aG docker {{WrapAsVariable "username"}};
{{if IsNSeriesSKU .}}
  {{GetGPUDriversInstallScript .}};
{{end}}
- mkdir -p /opt/azure/containers && touch /opt/azure/containers/runcmd.complete;
- echo `date`,`hostname`, endruncmd>>/opt/m;
{{end}}
